name: Deploy Castweather App
on:
  push:
    branches: [main]
permissions:
   contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Replace API key
      env: 
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        sed -i "s/OPENWEATHER_API_KEY_PLACEHOLDER/$OPENWEATHER_API_KEY/g" script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./